### ISSUE TITLE
failed extracting number from gif

### ISSUE THREAD

**Issue by haziri** [alimranahmed/LaraOCR#10]
Hi, i try to extract text from gif but i only got string "\f" [phoneno](https://www.mudah.my/pg/1Ge9AAciRMs/HfHIQQbAs4PK54qnaPwo=.gif?rna=3)

**Comment by haziri** [comment]
it seems that the image is too small. i've tried to increase the image size from width 50 (locking proportion) to 600 pixel but it become blur. is there any other way around this?

**Comment by alimranahmed** [comment]
I this package we have used tesseract OCR engine. The file you have shared doesn't contain any clear text or number. The file is too small and the numbers in the file is not even well recognisable by human. So, I don't think this OCR engine will be able to extract the texts from it.
