### ISSUE TITLE
How to detect spaces?

### ISSUE THREAD

**Issue by realtebo** [alimranahmed/LaraOCR#11]
I know this package is basic and not aimed to extract layout, but, when 'parsing' an order as image, I've shipment address and invoice address on two columns.

I got only text, so I've not idea on how to separated the first column chars from the second ones.

Is there a way to get at least tabs (\t) when there is a lot of space between texts?
Tesseract should be able to reconstrcut at least a minimum the layout.

**Comment by alimranahmed** [comment]
Yes, it will give you only the texts nothing else. We need to separate those text using programming logics. OCR engine is not meant to do that.
