### ISSUE TITLE
I want to get only vin number from image?

### ISSUE THREAD

**Issue by DalbirKaur** [alimranahmed/LaraOCR#13]
I am uploading the image but I am not getting an exact text from that image?

I am uploading the below image:
![images](https://user-images.githubusercontent.com/38942420/56809000-77514d00-6850-11e9-93aa-4485dceb8c99.jpeg)

and getting blow Parse text:
HED. IN JAPAN BY HONDA MOTOR CO. LTD: GVWR 4320.88 GAWR F 2160L8S R 2250.85 THIS VEHIGLE CONFORMS TO ALL APPLICABLE FEDERAL MOTOR VEHICLE SAFETY AND THEET PREVENTION STANDARDS. IN EFFECT ON THE DATE OF MANUFACTURE SHOWN ABOVE: “it JHLRD77874C026456 IULUQ.Y UVLO 

Thanks

**Comment by alimranahmed** [comment]
We need to make sure that the image is clear and good resolution. In the result you actually getting the vin with some other garbage text. I think you can grab the vin from there programmatically.

**Comment by DalbirKaur** [comment]
Thanks
