### ISSUE TITLE
Ocr for Laravel 5.8

### ISSUE THREAD

**Issue by averyH99** [alimranahmed/LaraOCR#14]
How to set it up properly in Laravel 5.8 version? Do you have any youtube tutorial for this one? Thank you

**Comment by alimranahmed** [comment]
Sorry, I don't have any video in youtube to setup this package. Check out the installation procedure [here](https://github.com/alimranahmed/LaraOCR#installation). Is there anything you are not clear about? Feel free to tell me the complexity you are facing. Thanks.

**Comment by Mfdsix** [comment]
I am use Laravel 5.8, and OCR::scan function didn't return anything, the response just Blank

**Comment by alimranahmed** [comment]
@Mfdsix 
Which operating system are you using? This package doesn't support Windows yet. Besides, make sure you have installed tesseract OCR engine correctly in your computer.
