### ISSUE TITLE
result of ocr is null

### ISSUE THREAD

**Issue by saidfeddaoui** [alimranahmed/LaraOCR#15]
hey,
when i call the scan function of Facade OCR i get result of null.

thanks,

**Comment by jahanzaib197** [comment]
Hey,
i scan my image using \OCR::scan($avatar) of facade OCR . it return null.
Thanks

**Comment by alimranahmed** [comment]
Which OS are you using? This package doesn't work as expected in Windows OS. 

Please make sure the tesserect is installed in your OS as mentioned in the readme file.
