### ISSUE TITLE
Composer require fails on non default namespace

### ISSUE THREAD

**Issue by vbasky** [alimranahmed/LaraOCR#16]
Composer require fails if you are not following the laravel recommended namespace convention

```
In OcrController.php line 10:

  Class 'App\Http\Controllers\Controller' not found
```

I don't have App as my namespace in this case the package is looking for 

> App\Http\Controllers

Laravel Version: 6.0

**Comment by alimranahmed** [comment]
I am not sure if I understood you correctly. The package is searching for the `Controller` class under the namespace `App\Http\Controllers`. It's where the `Controller` is available by default in Laravel, check  official Laravel code [here](https://github.com/laravel/laravel/blob/v6.8.0/app/Http/Controllers/Controller.php). Seems like you are have changed the namespace of `Controller` class that Laravel is used by default. By the way, to solve this problem, you can just change the namespace that used `Controller` class  in `OcrController` class. Besides, this controller, view are example to show how this package works which are not the original part of this package. The actual purpose of the package is to use OCR from any where of a Laravel project. 

Thanks for reaching out.
