### ISSUE TITLE
NO TEXT FOUND

### ISSUE THREAD

**Issue by patelmm** [alimranahmed/LaraOCR#18]
I have setup in laravel. I'm using macOS so install [tesseract](https://github.com/tesseract-ocr/tesseract/wiki#installation) and try to run demo. No text found can you please help out?

**Comment by alimranahmed** [comment]
Hi, 

Sorry for being so late. Can you share an image that you tried but not working so that I can make sure if it's in your machine or it's with the package.

**Comment by mohammadbax98** [comment]
Hi, I get the same result too. No Text Found.
I test with different images. simple, only number, text. with high quality, low quality...
for all of them, the result is same.

**Comment by alimranahmed** [comment]
@mohammadbax98 
Thanks for informing me. 
Have you tried the command `tesseract` in your terminal to make sure that you have `tesseract` installed correctly.

**Comment by kashif02018** [comment]
hi, can you help me, i am getting the same error, No Text Found

**Comment by alimranahmed** [comment]
@kashif02018 

Thanks for reporting. Have you checked considering my previous reply in this thread?

**Comment by kashif02018** [comment]
Please help
