### ISSUE TITLE
Pass language parameter to tesseract

### ISSUE THREAD

**Issue by Henning256** [alimranahmed/LaraOCR#21]
It would be great, if it was possible to pass the -l (language) parameter to the call of tesseract.
Using the right language when parsing a document with tesseract improves the result in most cases very much!

**Comment by alimranahmed** [comment]
@Henning256 

Thanks for opening this issue. 
Saw your PR and made a change request. Please give it a look.

**Comment by Henning256** [comment]
Hi @alimranahmed,
is there a release plan or something when things get merged from dev to master and when a new version gets released?

Cheers,
Henning
