### ISSUE TITLE
Getting Empty Resonse.

### ISSUE THREAD

**Issue by QasimInayat** [alimranahmed/LaraOCR#25]
I have tried all the approches that you have given in your code.
I am getting this response. 
""

PLEASE HELP ME OUT.

**Comment by yugnormand** [comment]
I have the same issue.

**Comment by Niteshcbsl** [comment]
Getting Empty Resonse.

**Comment by hafiezul** [comment]
Had "No Text Found" response for every image I tried but looks like installing Capture2Text on your system fixed the problem.

If you are using Windows and have Chocolatey installed, use this
`choco install capture2text --version 3.9`

**Comment by hafiezul** [comment]
> Getting Empty Resonse.

Had "No Text Found" response for every image I tried but looks like installing Capture2Text on your system fixed the problem.

If you are using Windows and have Chocolatey installed, use this
`choco install capture2text --version 3.9`

**Comment by mhamzase** [comment]
I'm also getting an empty response.

**Comment by mhamzase** [comment]
@hafiezul I have tested it after installing `Capture2Text`  on windows but still getting an empty response.

**Comment by notebook10** [comment]
no error but the response is empty ""

**Comment by ket-c** [comment]
MacOS Solution
1. Install MacPort https://guide.macports.org (use step 2.2.1 or step 2.2.2)
2. Install **tesseract** `sudo port install tesseract`
3. Install **tesseract engine** `sudo port install tesseract-eng`
4. cd to Laravel project
5. run `composer require alimranahmed/laraocr` in laravel project
6. run `php artisan vendor:publish`  in laravel project and choose **_Alimranahmed\LaraOCR\LaraOCRServiceProvider_**
Done!
