### ISSUE TITLE
i installed tesseract correctly and access able in cmd in project directory also but still getting empty response

### ISSUE THREAD

**Issue by sherz12r** [alimranahmed/LaraOCR#26]
please explain some details why it is not working for windows

**Comment by sherz12r** [comment]
please explain some details why it is not working for windows

**Comment by sherz12r** [comment]
even i tried your attached file but get empty response

**Comment by alimranahmed** [comment]
Hello,
For windows or any other OS you need to make sure that the Tesseract OCR is intalled. After installation make sure you can run the command `tesseract` from your CLI(eg. `cmd`). Only then this package is expected to work as it depends on that CLI command. 

To intall Tesseract-OCR in Windows you can have a look in this page: https://github.com/tesseract-ocr/tessdoc#binaries

**Comment by sherz12r** [comment]
I do all this but still getting empty responseSent from my iPhoneOn 9 Apr 2023, at 3:38 PM, Al Imran Ahmed ***@***.***> wrote:﻿
Hello,
For windows or any other OS you need to make sure that the Tesseract OCR is intalled. After installation make sure you can run the command tesseract from your CLI(eg. cmd). Only then this package is expected to work as it depends on that CLI command.
To intall Tesseract-OCR in Windows you can have a look in this page: https://github.com/tesseract-ocr/tessdoc#binaries

**Comment by alimranahmed** [comment]
Can you show me a screenshot of the output in your cmd when you execute `tesseract`?

**Comment by sherz12r** [comment]
Thanks brother today is working but on that day was not working I don’t know whySent from my iPhoneOn 10 Apr 2023, at 3:39 PM, Al Imran Ahmed ***@***.***> wrote:﻿
Can you show me a screenshot of the output in your cmd when you execute tesseract?

**Comment by sherz12r** [comment]
Image scanned now i want to compare text with the text extracted form image can you please guide how can i find specific text in extracted text bundle of thanks Sent from my iPhoneOn 10 Apr 2023, at 4:16 PM, sherz haider ***@***.***> wrote:﻿Thanks brother today is working but on that day was not working I don’t know whySent from my iPhoneOn 10 Apr 2023, at 3:39 PM, Al Imran Ahmed ***@***.***> wrote:﻿
Can you show me a screenshot of the output in your cmd when you execute tesseract?

**Comment by alimranahmed** [comment]
Sorry, this package only gives you the extracted data, you have to find your own way to parse only your requried data from the whole extracted data.

**Comment by sherz12r** [comment]
This will work on live server as it is or i have to install tesseract on live server also? Please guideSent from my iPhoneOn 10 Apr 2023, at 9:32 PM, Al Imran Ahmed ***@***.***> wrote:﻿
Closed #26 as completed.

**Comment by alimranahmed** [comment]
You have to install tesseract in the server too.

**Comment by sherz12r** [comment]
Ok thanks a lot brother Sent from my iPhoneOn 11 Apr 2023, at 12:32 PM, Al Imran Ahmed ***@***.***> wrote:﻿
You have to install tesseract in the server too.
